name: Python application

on:
  push:
  schedule:
    - cron:  '0 10 * * 1'

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-10.15]
        rust: [stable]

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sly
        sudo apt install flex bison wget
    - name: Build requirements
      run: |
        make requirements
    - name: Build gelpia
      run: |
        make
    - name: Get gelpia_tests
      run: |
        git clone https://github.com/soarlab/gelpia_tests.git
        cd gelpia_tests
        make
    - name: Run tests
      run: |
        cd gelpia_tests
        make test
